parameters:
- name: solutionPath
  type: string
  default: ''

steps:
- checkout: self
  clean: 'true'

- powershell: |
      dotnet nuget add source -n nuget_local $(Build.SourcesDirectory)\src\PackageCache
      dotnet nuget add source -n uno_dev "https://pkgs.dev.azure.com/uno-platform/1dd81cbd-cb35-41de-a570-b0df3571a196/_packaging/unoplatformdev/nuget/v3/index.json"

      Set-PSDebug -Trace 1
      
      if($env:System_PullRequest_TargetBranch -eq $null) { $TargetBranch = "master" } else { $TargetBranch = $env:System_PullRequest_TargetBranch; }
      git diff --quiet HEAD "origin/$TargetBranch" -- "${{ parameters.solutionPath }}"
      
      # Only build if there a change in the solution path for the current PR, if we're not in a PR
      if( ("$env:System_PullRequest_PullRequestId" -eq '') -or ($global:LASTEXITCODE -ne 0)) {
        
        & $env:msbuildpath ${{ parameters.solutionPath }} /r /p:Configuration=Release /p:WasmShellMonoRuntimeExecutionMode=Interpreter /p:AotAssemblies=false /p:PublishTrimmed=false /p:WasmShellILLinkerEnabled=false /ds ;
        
        if (($lastexitcode -ne 0)) {
          exit $lastexitcode
        }

        # Clean the whole tree after every build to avoid disk space issues
        git clean -fdx
      }    
  displayName: Build Matrix Samples
